---
- name: Ping Kubernetes nodes
  hosts: node
  remote_user: shlomob
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
    - name: Ping hosts
      ping:

# command to run playbook:
# ansible-playbook -i /home/shlomob/my-cluster/hosts /home/shlomob/my-cluster/ping.yml

# ---
# - name: Ping Kubernetes nodes
#   hosts: master
#   remote_user: shlomob
#   gather_facts: false
  
#   tasks:
#     - name: Ping hosts
#       ping:

# # command to run playbook:
# # ansible-playbook -i /home/shlomob/my-cluster/hosts.ini /home/shlomob/my-cluster/ping.yml