# ---
# - name: Ping Kubernetes nodes
#   hosts: node
#   remote_user: shlomob
#   gather_facts: false
#   vars:
#     ansible_python_interpreter: /usr/bin/python3
  
#   tasks:
#     - name: Ping hosts
#       ping:
---
- name: Ping Kubernetes nodes
  hosts: master
  remote_user: shlomob
  gather_facts: false
  
  tasks:
    - name: Ping hosts
      ping:


# command to run playbook to ping worker nodes:
# ansible-playbook -i hosts ping.yml

# command to run playbook to ping master nodes:
# ansible-playbook -i hosts.ini ping.yml

# command to run playbook to deploy k3s:
# ansible-playbook site.yml -i hosts.ini -vvv

# command to run playbook to reset k3s:
# ansible-playbook reset.yml -i hosts.ini -vvv